### PR TITLE
Error message fix/testing

### LINKED ISSUE #280: Update error message
image

Update the command and the UG

### PR DESCRIPTION
**Pull request by sjoann**
Fixes #280 
More test cases for time range to be included

### CODE REVIEW

File: src/main/java/seedu/address/model/student/Class.java [hunk 1]
```diff
@@ -25,8 +25,7 @@ public class Class {
             "Time should be in a valid time in the range of 0000 - 2359";
     public static final String INVALID_DATETIME_ERROR_MESSAGE =
             INVALID_DATE_ERROR_MESSAGE + ".\n" + INVALID_TIME_ERROR_MESSAGE;
-    public static final String INVALID_DURATION_ERROR_MESSAGE = "EndTime must be after StartTime and duration"
-            + " should be less than or equal to the difference between EndTime and StartTime";
+    public static final String INVALID_DURATION_ERROR_MESSAGE = "EndTime must be after StartTime";
```
Comment (seanflyyy) [inline src/main/java/seedu/address/model/student/Class.java:28]: Thanks for fixing this!

File: src/main/java/seedu/address/model/student/Class.java [hunk 2]
```diff
@@ -331,12 +336,12 @@ public boolean equals(Object other) {
...
-     * {@code Class} and {@code aclass} must be non-null;
+     * Returns 1 if this {@code Class} starts before the given {@code aClass}.
+     * {@code Class} and {@code aClass} must be non-null;
      */
-    public int compareToByStartTime(Class aclass) {
-        requireAllNonNull(this.startTime, aclass.startTime);
-        return this.startTime.compareTo(aclass.startTime);
+    public int compareToByStartTime(Class aClass) {
+        requireAllNonNull(this.startTime, aClass.startTime);
+        return this.startTime.compareTo(aClass.startTime);
```
Comment (seanflyyy) [inline src/main/java/seedu/address/model/student/Class.java:344]: Fantastic catch!

**Review by seanflyyy — APPROVED** [review]
LGTM!

Thanks for adding test cases and fixing the JavaDoc formatting issues.

Just a tip, as mentioned privately, separating the different tasks you are addressing into individual PRs would help with version control!

Other than that, really appreciate the adding of the test cases and fixing the error message! 

Good job :D

**Comment by seanflyyy** [comment]
Close #329
