### PR TITLE
Find by address fix from bug report

### LINKED ISSUE #253: [PE-D][Tester E] Find by address
`find a/29` does not work, despite `Alex Yeoh` having address `Blk 30 Geylang Street 29, #06-40`. Find `a/29` should match the `29` in `Street 29`. Same for

`find a/74`
`find a/26` 

on the addresses `Blk 11 Ang Mo Kio Street 74, #11-04` and `Blk 436 Serangoon Gardens Street 26, #16-43`.

I understand that this is likely because `74` does not match with `74,` (with the comma) but is this the intended behaviour of `find`?

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ryanlml/ped#3

### PR DESCRIPTION
**Pull request by gnahzeus**
Closes #253

### CODE REVIEW

File: src/main/java/seedu/address/model/student/Address.java [hunk 1]
```diff
@@ -9,7 +9,7 @@
  */
 public class Address {
 
-    public static final String MESSAGE_CONSTRAINTS = "Addresses can take any values, and it should not be blank";
+    public static final String MESSAGE_CONSTRAINTS = "Addresses can take any values, but it should not be blank";
```
Comment (Echomo-Xinyu) [inline src/main/java/seedu/address/model/student/Address.java:12]: Good catch!

**Review by Echomo-Xinyu — APPROVED** [review]
Very impressive catch for grammar and spacing! Good to see you have converted the `stream()` to `if` block for clear logic! Good work!
