### PR TITLE
Initialise class bug

### LINKED ISSUE #242: [PE-D][Tester D] Editing the data file does not perform proper data validation.
According to the user guide, changes to the data file would catch invalid data formats, but it is currently possible to tweak the data to create undesired scenarios, e.g. conflicting items in the schedule list

As we can see, both slots overlap. A possible fix is to perform a simple validation of the data when loading it from the JSON file.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: ngxingyu/ped#1

### PR DESCRIPTION
**Pull request by sjoann**
- Empty out json file if there is a class conflict
- Minor updates on the javadocs
- Fixes #242

### CODE REVIEW

**Comment by Echomo-Xinyu** [comment]
The code looks very clean and I appreciate it!

But I am not very sure about the intended effect of this PR. Will it create an empty teacher's pet whenever the data gets modified or only when there is a class conflict? What if the change is against our implementation but still holds valid for class conflict?

For example, when you set the default list of students to have `Alex` having a lesson on `1-2 am today (1 Nov)` and `Bernice` having a lesson on `8-9 am today`. When you close the app, modify the `displayClass` field to `11 Nov`, and reopen the application, Bernice will still be displayed in the `Schedule List`. But when you `mark Bernice`, the corresponding `class date` of `Bernice` will be changed to 18 Nov.

I do not see a very easy fix for this problem and therefore, I would recommend that we discourage any change of data files by users manually. ie We are not responsible for any manual modification to the data files. What do yall think? @seanflyyy @cadencjk @gnahzeus

**Comment by seanflyyy** [comment]
> The code looks very clean and I appreciate it!
> 
> But I am not very sure about the intended effect of this PR. Will it create an empty teacher's pet whenever the data gets modified or only when there is a class conflict? What if the change is against our implementation but still holds valid for class conflict?
> 
> For example, when you set the default list of students to have `Alex` having a lesson on `1-2 am today (1 Nov)` and `Bernice` having a lesson on `8-9 am today`. When you close the app, modify the `displayClass` field to `11 Nov`, and reopen the application, Bernice will **still** be displayed in the `Schedule List`. But when you `mark Bernice`, the corresponding `class date` of `Bernice` will be changed to 18 Nov.
> 
> I do not see a very easy fix for this problem and therefore, I would recommend that we discourage any change of data files by users manually. ie We are not responsible for any manual modification to the data files. What do yall think? @seanflyyy @cadencjk @gnahzeus

Thanks for reviewing this code @Echomo-Xinyu! I took a look too and yes, it seems that when I modify the code to lead to a conflict, it wipes the entire file. I don't think this is the most elegant solution. I think it makes more sense to just restore the changes to the previous state, but this will involve some level of version control. I think that in this case, wiping the entire database seems too drastic a solution.

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -199,10 +202,18 @@ private CommandResult executeCommand(String commandText) throws CommandException
...
             resultDisplay.setFeedbackToUser(e.getMessage());
             throw e;
         }
     }
+
+    /**
+     * Displays error message to user when there is invalid format in the teachersPet json file.
+     */
+    public void showInvalidFormatInJsonFile() {
+        resultDisplay.setFeedbackToUser("JSON file is invalid. File will not be saved until the error is corrected."
```
Comment (Echomo-Xinyu) [inline src/main/java/seedu/address/ui/MainWindow.java:216]: I think it would be better to make it not a magical literal by declaring it as a private static variable.

File: src/main/java/seedu/address/ui/Ui.java [hunk 2]
```diff
@@ -10,4 +10,6 @@ public interface Ui {
     /** Starts the UI (and the App).  */
     void start(Stage primaryStage);
 
+    void showInvalidFormatInJsonFile();
```
Comment (Echomo-Xinyu) [inline src/main/java/seedu/address/ui/Ui.java:13]: I think the naming of the function can be changed to "displayInvalidJsonFileMessage()" to improve readability. Otherwise, I would expect this function to point out where goes wrong with the JSON file in format.

**Review by Echomo-Xinyu — APPROVED** [review]
A great PR with really a lot of effort! I especially like the test case! very well written!

I feel that the error message can be more detailed in terms of the possible actions that can be taken by the user. ie I think it would be good to specify that there are two options to the user: to revert any change to json file if they still want the data, or delete json if they want a fresh restart.

I think I also need to do some more testing on @cadencjk 's PR as they may potentially affect each other. But so far this PR looks great! Keep up the good work!

**Comment by cadencjk** [comment]
> A great PR with really a lot of effort! I especially like the test case! very well written!
> 
> 
> 
> I feel that the error message can be more detailed in terms of the possible actions that can be taken by the user. ie I think it would be good to specify that there are two options to the user: to revert any change to json file if they still want the data, or delete json if they want a fresh restart.
> 
> 
> 
> I think I also need to do some more testing on @cadencjk 's PR as they may potentially affect each other. But so far this PR looks great! Keep up the good work!

In my latest PR I have removed the displayDate field, so now every person only has a classDateTime field. I don't think mine will affect this, but will confirm when it's merged.

File: src/main/java/seedu/address/ui/Ui.java (hunk 2 above)
Comment (sjoann) [reply src/main/java/seedu/address/ui/Ui.java:13]: that's a good point ! i will change it
