### PR TITLE
Fix int overflow bug in statistics window

### LINKED ISSUE #97: Statistics int overflow bug
When the sum of the moneyOwed/moneyPaid is too large, the statistics shown will be wrong:

Test case:
`edit 1 owed/2147483646`
`edit 2 owed/300`
Will return money owed as `$-2147483350`, which is unexpected

### PR DESCRIPTION
**Pull request by cadencjk**
Should the sum of the amount owed/paid overflow the maximum integer value, the statistics will show a String warning message instead of an incorrect negative number.

Fixes #97

### CODE REVIEW

File: src/main/java/seedu/address/model/StatisticsCalculator.java [hunk 1]
```diff
@@ -33,24 +33,32 @@ public int getSize() {
     /**
      * Sums up the total money owed by the people in AddressBook.
```
Comment (gnahzeus) [inline src/main/java/seedu/address/model/StatisticsCalculator.java:34]: Seems like getAmountOwed() and getAmountPaid() comments are missing the return tag?

**Review by gnahzeus — APPROVED** [review]
LGTM! Might want to consider adding in the comment tags, but otherwise, it's good to go.

File: src/main/java/seedu/address/model/StatisticsCalculator.java (hunk 1 above)
Comment (cadencjk) [reply src/main/java/seedu/address/model/StatisticsCalculator.java:36]: Oops missed out, have updated it!
